### ISSUE TITLE
Font Color?

### ISSUE THREAD

**Issue by jonathanwichter** [michaellee/open-hours#1]
How do I change the font color?
<img width="2518" alt="screen shot 2018-06-14 at 10 26 15 am" src="https://user-images.githubusercontent.com/35083828/41418299-6dc9fdc2-6fbd-11e8-85da-e5a135466ce6.png">

**Comment by michaellee** [comment]
Hey hey @jonathanwichter super cool that you're using my script.

So, as far as I can see the script shouldn't introduce any color when it is rendered in the DOM. Meaning it should just inherit whatever body color is set in the CSS. If you followed the instructions and used the `<div id="open-hours"></div>` element. You can target `open-hours` in your CSS like this:

```
#open-hours {
  color: white
}
```

By the way, curious how you found this repo?

**Comment by jonathanwichter** [comment]
Thanks for getting back to me. I got if off of Github search.

 

 

Thanks,

Jonathan D Wichter

**Comment by michaellee** [comment]
Very cool! Good luck with your project :)

**Comment by jonathanwichter** [comment]
Here is your script in action on my site. http://siberianhuskywebdesignsinc.com/ Click on the contact link on the menu and you will see it their.

 

Thanks,

Jonathan Wichter
